Feature/user closest restaurants
Restazo/user.api pull request #4
Opened 2024-03-26 13:26 UTC by RepoRover

Adding restaurants near you endpoint to production

2024-03-27 18:23 UTC, Matheus-OAMK requested changes

2024-03-27 18:23 UTC, Matheus-OAMK commented on src/schemas/restaurantsNearYouReq.ts
I see that you intend for user_lat and user_lon to be required on this schema. This implementation wont work as intended. 

In case parameters ARE there but empty(empty string). It will still be parsed successfully.
Example restaurant?user_lat=?&user_lon=&range=200      //  sucess

You can just chain z.string().min(1) in user_lat and user_lon, this way it checks if they're also empty.

2024-03-27 18:23 UTC, Matheus-OAMK commented on src/controllers/restaurantsController.ts
> +  const userLatitude = Number(validatedRequest.data.user_lat);
When you Number() an empty string it coerces it to 0.

After this you check if isNaN which 0 is a number so it passes this check too.

You can fix this with my other comment in your schema, by making sure empty strings are caught in the zod parsing

2024-03-27 18:31 UTC, Matheus-OAMK commented
An idea would also be to include default values or latitude or longitude. Incase they're missing...
Could also be implemented in the client side instead

2024-03-31 16:44 UTC, HamidrezaYourdkhani1993 approved these changes

2024-03-31 16:45 UTC, HamidrezaYourdkhani1993 approved these changes

2024-03-31 16:48 UTC, NimbleNinjaa approved these changes

2024-03-31 16:55 UTC, HamidrezaYourdkhani1993 approved these changes
according to my understanding, this SQL query snippet is used to find all 'listed' restaurants within a specified maximum distance from a given point, joining data from a restaurant's details table with its address table, and then ordering the results by distance

2024-03-31 17:45 UTC, Matheus-OAMK approved these changes

2024-03-31 17:50 UTC, merged